import FeMaleDoctor from "../../assets/images/female-doctor.png";
import MaleDoctor from "../../assets/images/male-doctor.png";
import { Doctor } from "./types";

export const doctors: Doctor[] = [
  {
    name: "Анеля Торалиева",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#5865F2",
    avatar: FeMaleDoctor,
    doctorId: 1,
    events: [
      {
        appointmentId: 0,
        startTime: "2025-01-03T14:00:00.858Z",
        endTime: "2025-01-03T15:40:00.858Z",
        description: "string",
        appointmentStatus: "CANCELED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 30,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-28T11:00:00.858Z",
        endTime: "2024-12-28T12:00:00.858Z",
        description: "string",
        appointmentStatus: "CANCELED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 60,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-25T13:00:00.858Z",
        endTime: "2024-12-25T15:00:00.858Z",
        description: "string",
        appointmentStatus: "CANCELED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 120,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Максат Аманов",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#25BE22",
    avatar: MaleDoctor,
    doctorId: 2,
  },
  {
    name: "Ажар Осмоналиева",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#3745D4",
    avatar: FeMaleDoctor,
    doctorId: 3,
    events: [
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:00:45.858Z",
        endTime: "2024-12-28T14:05:45.858Z",
        description: "string",
        appointmentStatus: "COMPLETED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 15,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:05:45.858Z",
        endTime: "2024-12-28T14:05:45.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 0,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Алтынбек Жумадил уулу",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#D80E0C",
    avatar: MaleDoctor,
    doctorId: 4,
    events: [
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:05:45.858Z",
        endTime: "2024-12-28T14:05:45.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 0,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:00:00.858Z",
        endTime: "2024-12-28T14:30:00.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 0,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Алтынбек Жумадил уулу",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#D80E0C",
    avatar: MaleDoctor,
    doctorId: 5,
    events: [
      {
        appointmentId: 0,
        startTime: "2024-12-28T16:00:00.858Z",
        endTime: "2024-12-28T18:00:45.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 120,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:05:45.858Z",
        endTime: "2024-12-28T14:05:45.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 0,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Рахит Шарипов",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#F4CE36",
    avatar: FeMaleDoctor,
    doctorId: 6,
  },
  {
    name: "Сыймык Караев",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#0EA5E9",
    avatar: MaleDoctor,
    doctorId: 7,
  },
  {
    name: "Ажар Осмоналиева",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#3745D4",
    avatar: FeMaleDoctor,
    doctorId: 8,
    events: [
      {
        appointmentId: 0,
        startTime: "2024-12-28T11:30:00.858Z",
        endTime: "2024-12-28T12:00:00.858Z",
        description: "string",
        appointmentStatus: "NOT_CONFIRMED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 30,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Алтынбек Жумадил уулу",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#D80E0C",
    avatar: MaleDoctor,
    doctorId: 9,
  },
  {
    name: "Алтынбек Жумадил уулу",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#D80E0C",
    avatar: MaleDoctor,
    doctorId: 10,
    events: [
      {
        appointmentId: 0,
        startTime: "2024-12-28T11:00:00.858Z",
        endTime: "2024-12-28T15:00:00.858Z",
        description: "string",
        appointmentStatus: "NOT_WORKED",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "Не работает",
            price: 0,
            duration: 1440,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
      {
        appointmentId: 0,
        startTime: "2024-12-28T14:05:45.858Z",
        endTime: "2024-12-28T14:05:45.858Z",
        description: "string",
        appointmentStatus: "IN_PROCESSING",
        userId: 0,
        userFirstName: "string",
        userLastName: "string",
        userPhoneNumber: "string",
        masterId: 0,
        masterFirstName: "string",
        masterLastName: "string",
        services: [
          {
            id: 0,
            name: "string",
            price: 0,
            duration: 0,
            type: true,
          },
        ],
        numberOfVisits: 0,
        promocode: "string",
        unregistered: true,
      },
    ],
  },
  {
    name: "Рахит Шарипов",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#F4CE36",
    avatar: FeMaleDoctor,
    doctorId: 11,
  },
  {
    name: "Сыймык Караев",
    specialty: "Терапевт",
    schedule: "10:00 - 20:00",
    color: "#0EA5E9",
    avatar: MaleDoctor,
    doctorId: 711,
  },
];
